#!/usr/bin/env sh

# rm -rf ~/.vim/plugged

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall +qall

cd ~/.vim/plugged/YouCompleteMe
git submodule update --init --recursive
./install.sh

cd ~/.vim/plugged/vimproc.vim
make
